Initial pull request for AMAND
msu-evrl/AMAND pull request #1
Opened 2019-06-27 19:55 UTC by BIGDADDYDAVID47

2019-06-28 13:40 UTC, knwachuk requested changes
You should make the name of the file reflect what the file is actually supposed to do:

e.g. drone_motion.ino, motion_control.ino, etc. That way, a cursory view of your files should be able to key you into their function.

Second, your branch names should reflect the purpose of the branch.

2019-06-28 13:41 UTC, knwachuk commented on final_code_for_sympossium.ino
> +
Also yo should remove our demo spaces before committing the file.

2019-07-01 15:34 UTC, TheLegacyE requested changes
Spaces are still in the code, please remove.

2019-07-01 16:00 UTC, TheLegacyE approved these changes

2019-07-01 16:02 UTC, merged